#version: '3.9'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  agent_journalist:
    build: ./agent_journalist
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  agent_editor:
    build: ./agent_editor
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq

  controller:
    build: ./controller
    environment:
      - RABBIT_HOST=rabbitmq
    depends_on:
      - rabbitmq
    stdin_open: true
    tty: true
